### ISSUE TITLE
LuaRocks

### ISSUE THREAD

**Issue by catwell** [zserge/lua-promises#1]
Hello,

any chance you would add a rockspec and put this into LuaRocks?

**Comment by zserge** [comment]
To be honest, I never used LuaRocks (yet), but I got a similar request for my another Lua library (lua-sh), so I think it's time to learn :) Any hints/guidelines are welcome!

**Comment by catwell** [comment]
It is very easy for simple libraries like this. The best thing to do is to have two versions of the rock: one with the development version (called SCM) and one for releases. You can find rockspec examples from one of my own libraries [here](https://github.com/catwell/haricot/tree/master/rockspec). For stable releases, you can choose to host the source in a tarball like I did for [Haricot release 1.0](https://github.com/catwell/haricot/blob/master/rockspec/haricot-1.0-1.rockspec#L4-L7) or just use Git like I did for [Haricot release 1.1](https://github.com/catwell/haricot/blob/master/rockspec/haricot-1.1-1.rockspec#L4-L7) (the "branch" can be a simple tag).

Once this is done, register on luarocks.org, install luarocks and use the `luarocks upload` command. It is not necessary to upload the SCM rock, you can just leave the rockspec on GitHub (it can be installed using the URL for the raw rockspec file).

**Comment by zserge** [comment]
Thanks for the links! It was really easy. I published the 'scm' variant only, since there is no other versions yet. Seems to be working (I was able to install it via luarocks).

**Comment by catwell** [comment]
Yes, it works. Users have to specify `--server=http://luarocks.org/dev` because it is a SCM version, but that is expected. Thank you!
