### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by alkino** [zserge/lua-promises#7]
Hi o/
If you create a gh-pages branch I can submit my PR with the ldoc generated.
You can see it here : https://alkino.github.io/lua-promises/
Regards,
alkino

**Comment by zserge** [comment]
@alkino First of all, thank you for the PRs! As for the `gh-pages` branch I wonder if the `docs` folder would work? I'd prefer to keep docs and code together, and I think github supports web pages served from the `docs` folder: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by alkino** [comment]
If you don't mind add generated files to your master branches. I think it's ok.
